import { Inter } from 'next/font/google';
import dynamic from 'next/dynamic';

// Carga el Navbar y el Footer dinámicamente solo en el cliente
const Navbar = dynamic(() => import('./components/Navbar/navbar'), {
  ssr: false,
});

const Footer = dynamic(() => import('./components/Footer/Footer'), {
  ssr: false,
});

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'latanNews',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>LatamNews</title>
      </head>
      <body className={inter.className}>
       <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
