import { Inter } from 'next/font/google';
import Footer from './components/Footer/Footer';
import Navbar from './components/Navbar/navbar';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'latanNews',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>LatamNews</title>
      </head>
      <body className={inter.className}>
       <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
